export const DB_DOCUMENT_NOT_FOUND = 'DB_DOCUMENT_NOT_FOUND';
export const TYPE_ERROR = 'TYPE_ERROR';
export const INVALID_REQUEST_PARAM = 'INVALID_REQUEST_PARAM';
export const MONGOOSE_ERROR = 'MONGOOSE_ERROR';
export const MONGOOSE_VALIDATION_ERROR = 'MONGOOSE_VALIDATION_ERROR';
export const GENERIC = 'GENERIC';
