module.exports = {
    DB_DOCUMENT_NOT_FOUND: 'DB_DOCUMENT_NOT_FOUND',
    TYPE_ERROR: 'TYPE_ERROR',
    INVALID_REQUEST_PARAM: 'INVALID_REQUEST_PARAM',
    MONGOOSE_ERROR: 'MONGOOSE_ERROR',
    MONGOOSE_VALIDATION_ERROR: 'MONGOOSE_VALIDATION_ERROR',
    GENERIC: 'GENERIC',
};
