export default [
    "I don't have friends. I got family",
    'Ogres are like onions',
    "You're my boy, Blue!",
    'Jessica, only child, Illinois, Chicago',
    'You have bewitched me, body and soul',
    "So be prepared, be enthusiastic,&nbsp;and leave your bullshit attitude and baggage at the door because we don't need it!",
    'I just wanted to take another look at you',
    "You gotta hear this one song. It'll change your life, I swear",
    'This is how I win',
    "You've got red on you",
    'Honest to blog?',
    'I am Groot',
    'Put some Windex on it',
    'It is the <em>titular</em> role!',
    'I want to play a game',
    'They called me Mr. Glass',
    'I have nipples, Greg. Could&nbsp;you milk me?',
    'This is Sparta!',
    'In one of our designs even these mosquito bites will look like juicy, juicy mangoes!',
    'I wanna rob',
    "You're putting the pussy on a pedestal",
    "Cello, you've got a bass",
    'I am gonna kill Bill',
    "Didn't I tell you not to come to my house? Nobody touches my child!",
    'We could not talk or talk forever and still find things to not talk about',
    "Why'd y'spill yer beans?",
    'Hell is a teenage girl',
    'You gonna eat your tots?',
    "I have had it with these motherfuckin' snakes on this motherfuckin' plane!",
    'To me, you are perfect',
    'For a guy with a four digit IQ, I must have missed something',
    'My tastes are very singular',
    'I have to return some videotapes',
    "Do you know what happens to a toad when it's struck by lightning? The same thing that happens to everything else",
    'In moonlight, black boys look blue',
    'These are not spirit fingers. <u>These</u>&nbsp;are spirit fingers. And these are gold',
    'The law says that you cannot touch.&nbsp;But I think I see a lot of lawbreakers up in this house tonight',
    "You're a wizard, &#8216;arry",
    "I'm the guy who does his job. You must be the other guy",
    'Look at my shit',
    'Prepare to be fucked by the long dick of the law!',
    'Just keep swimming',
    'You had my curiosity. But now you have my attention',
    "You're the man now, dog!",
    "Girl, you can't get no infection in your booty hole! It's a booty hole!",
    'I volunteer as tribute',
    'Even artichokes have hearts',
    'Would that it were so simple',
    'With great power comes great responsibility',
    'Ass to ass',
    'You will ride eternal, shiny and chrome',
    "I don't like sand. It's all coarse, and rough, and irritating. And it gets everywhere",
    'I am the motherfucker that found this place, sir',
    'Kiss me, my girl, before I am sick',
    'The wrong kid died',
    'Not the bees!',
    "I'm glad he's single because I'm going to climb that like a tree",
    'Are you watching closely?',
    'Dear 8-pound, 6-ounce newborn infant Jesus&#8230;',
    'Man, fuck Jesse Jackson!',
    'Would it be all right if I showed the children the whoring bed?',
    'I was perfect',
    "That's a bingo",
    'Why are you wearing that stupid man suit?',
    'I know that babies taste the best',
    "Honey? Where's my super suit?",
    'What is this? A center for ants?',
    'Meet me in Montauk',
    "It's the fucking Catalina Wine Mixer",
    'Rock stars have kidnapped my son!',
    'Not quite my tempo',
    'Wilsoooooooon!',
    "Now you're in the sunken place",
    'Why so serious?',
    'Difficult difficult lemon difficult',
    "I won't say it for Little Baby Ears over there, but it rhymes with &#8216;smushmortion.'",
    'Is this your king?',
    "If you're a bird, I'm a bird",
    'I am Shiva, the god of death',
    "I'm gonna steal the Declaration of Independence",
    'You shall not pass!',
    "If anyone orders merlot, I'm leaving. I am <u><em>not</em></u> drinking any fucking merlot!",
    'But what I do have are a very particular set of skills, skills I have acquired over a very long career, skills that make me a nightmare for people like you',
    'Look at me. Look at me. I am the captain now',
    'Baby, you are gonna miss that plane',
    'My wife!',
    'Are you not entertained?',
    'You sit on a throne of lies',
    'Wouldst thou like to live deliciously?',
    "Exercise gives you endorphins. Endorphins make you happy. Happy people just don't shoot their husbands, they just don't",
    "You're tearing me apart, Lisa!",
    "I'm a fiend for mojitos",
    'Boy, that escalated quickly',
    "King Kong ain't got shit on me!",
    'I live my life a quarter mile at a time',
    "A million dollars isn't cool. You know what's cool?",
    "She doesn't even go here!",
    'I wish I knew how to quit you',
    'Florals? For spring? Groundbreaking',
    'I drink your milkshake',
];
