services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - APP_FOLDER=apps/api
        - APP_NAME=api
        - PORT=15101
        - NODE_ENV=production
    ports:
      - "15101:15101"
    environment:
      - NODE_ENV=production
      - PORT=15101
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15101/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./apps/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    depends_on:
      - api

volumes:
  caddy_data:
  caddy_config:

networks:
  app_network:
    driver: bridge