#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint && npm test
. ./setMainFolder.sh
cd $MAIN/view/landing && npm run lint && npm test
cd $MAIN/view/react-projects && npm run lint && CI=true npm test