#!/bin/sh


#
# TODO: setup husky, commenting until lerna repo is stable
#

# . "$(dirname "$0")/_/husky.sh"
# 
# npm run lint
# . ./setMainFolder.sh
# cd $MAIN/view/landing && npm run lint
# cd $MAIN/view/react-projects && npm run lint