services:
  api:
    image: avatarkorranika/portfolio-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "5001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@172.17.0.1:5433/postgres
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  # Named volume for SQLite database persistence
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge
